/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lee.view;

import com.lee.member.model.MemberDAO;
import com.lee.member.model.MemberDTO;
import com.lee.member.model.MemberService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author my
 */
public class MemberGUI extends javax.swing.JFrame implements ActionListener{
    private MemberDAO memberDao;
    private LoginGUI loginGui;
    private boolean duplicateChecked; //중복확인 했으면 true
    
    /**
     * Creates new form MemberGUI
     */
    public MemberGUI() {
        initComponents();
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPhone2 = new javax.swing.JTextField();
        btReg = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        cbPhone1 = new javax.swing.JComboBox<>();
        tfPhone3 = new javax.swing.JTextField();
        tfuserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfuserId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btDup = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("회원가입");

        jLabel1.setText("이름");

        jLabel4.setText("전화번호");
        jLabel4.setMaximumSize(new java.awt.Dimension(55, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(55, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(55, 17));

        tfPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhone2ActionPerformed(evt);
            }
        });

        btReg.setBackground(new java.awt.Color(204, 204, 204));
        btReg.setText("회원가입");

        btCancel.setBackground(new java.awt.Color(204, 204, 204));
        btCancel.setText("취소");

        cbPhone1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "010", "011", "016", "017", "019" }));
        cbPhone1.setMinimumSize(new java.awt.Dimension(72, 25));

        tfPhone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhone3ActionPerformed(evt);
            }
        });

        tfuserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserNameActionPerformed(evt);
            }
        });

        jLabel5.setText("아이디");

        tfuserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserIdActionPerformed(evt);
            }
        });

        jLabel7.setText("비밀번호");
        jLabel7.setMaximumSize(new java.awt.Dimension(55, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(55, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(55, 17));

        btDup.setBackground(new java.awt.Color(204, 204, 204));
        btDup.setText("중복확인");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfPassword)
                                        .addGap(3, 3, 3))
                                    .addComponent(tfuserId, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(tfPhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btDup, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btReg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfPhone2)
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfuserId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPhone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btReg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhone2ActionPerformed

    private void tfPhone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhone3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhone3ActionPerformed

    private void tfuserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserNameActionPerformed

    private void tfuserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDup;
    private javax.swing.JButton btReg;
    private javax.swing.JComboBox<String> cbPhone1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPhone2;
    private javax.swing.JTextField tfPhone3;
    private javax.swing.JTextField tfuserId;
    private javax.swing.JTextField tfuserName;
    // End of variables declaration//GEN-END:variables

    private void init() {
        memberDao=new MemberDAO();
        duplicateChecked=false;
        
    }

    private void addEvent() {
        btReg.addActionListener(this);
        btCancel.addActionListener(this);
        btDup.addActionListener(this);
        tfuserId.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btDup || e.getSource()==tfuserId){
            String userId=tfuserId.getText();
            if(userId==null || userId.isEmpty()){
                JOptionPane.showMessageDialog(this, "아이디를 입력하세요");
                tfuserId.requestFocus();
                return;
            }
            
            try {
                int result=memberDao.duplicate(userId);
                if(result==MemberService.USABLE_ID){
                    int type=JOptionPane.showConfirmDialog(this, "사용가능한 아이디 입니다, 사용하시겠습니까?",
                            "아이디 확인",JOptionPane.YES_NO_OPTION);
                    if(type==0){
                        duplicateChecked=true;
                    }else{
                        tfuserId.setText("");
                        tfuserId.requestFocus();
                        return;
                    }
                }else if(result==MemberService.NON_USABLE_ID){
                    JOptionPane.showMessageDialog(this, "이미 사용중인 아이디입니다, 다른 아이디를 입력해주세요");
                    tfuserId.requestFocus();
                    return;
                }else{
                    JOptionPane.showMessageDialog(this, "아이디 확인 불가");
                    return;
                }
            } catch (SQLException ex) {
                Logger.getLogger(MemberGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(e.getSource()==btReg){
            try {
                register();
            } catch (SQLException ex) {
                Logger.getLogger(MemberGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(e.getSource()==btCancel){
            this.dispose();
        }
    }

    private void register() throws SQLException {
        String name=tfuserName.getText();
            String id=tfuserId.getText();
            String pwd=tfPassword.getText();
            String phone1=cbPhone1.getSelectedItem().toString();
            String phone2=tfPhone2.getText();
            String phone3=tfPhone3.getText();
            
            if(name==null || name.isEmpty()){
                JOptionPane.showMessageDialog(this, "이름을 입력해주세요");
                tfuserName.requestFocus();
                return;
            }
            if(id==null || id.isEmpty()){
                JOptionPane.showMessageDialog(this, "아이디를 입력해주세요");
                tfuserId.requestFocus();
                return;
            }
            if(pwd==null || pwd.isEmpty()){
                JOptionPane.showMessageDialog(this, "비밀번호를 입력해주세요");
                tfPassword.requestFocus();
                return;
            }
            if(!duplicateChecked){
                JOptionPane.showMessageDialog(this, "아이디 중복확인해주세요");
                tfuserId.requestFocus();
                return;
            }
            
            String phone="";
            if((phone2!=null&&!phone2.isEmpty()) &&(phone3!=null)&&!phone3.isEmpty())
                phone=phone1+"-"+phone2+"-"+phone3;
            
            MemberDTO dto=new MemberDTO();
            dto.setName(name);
            dto.setUserid(id);
            dto.setPwd(pwd);
            dto.setPhone(phone);
            
            int cnt=memberDao.insertMember(dto);
            
            String msg="";
            if(cnt>0){
                msg="회원가입 완료";
                this.dispose();
            }else{
                msg="회원가입 실패, 다시 실행해주세요";
            }
            JOptionPane.showMessageDialog(this, msg);
    }
}
